### ISSUE TITLE
[SA] can not place a packed memory unit in remote view ?

### ISSUE THREAD

**Issue by DancingDolphins** [notnotmelon/deep-storage-unit#12]
If I [alt+D] a building in romote view .I got a packed item .which store in my yellow chest,
but I cant place it out in remote view.
maybe add a packed item in ghost mode ?

**Comment by notnotmelon** [comment]
Sorry, this is too difficult due to technical reasons.

**Comment by Akino-Ovsky** [comment]
Has there been any update on this being doable now? Just wondering as it's been a good few months after release and stuff may be more researched and a possible fix found

caaaaaaaaaaaaaause I just picked up an MU with 1.2m prometheum ore in it... and I can't ship the MU down and make the science on the surface nor place it back down to just... yknow undo picking it up
My only option I can find right now is to literally send up TENS OF THOUSANDS of rockets, 10 prometheum chunks at a time

**Comment by notnotmelon** [comment]
It's a difficult problem to solve. The game engine just sees "memory unit item in chest". There's no way to tell the construction bots to differentiate based on item metadata. I would have to do something very hacky with scripts.
