### ISSUE TITLE
Add support for circuit signal networks

### ISSUE THREAD

**Issue by AutumnPizazz** [notnotmelon/deep-storage-unit#14]
Hello! I really like your mod and I hope to add a feature to the "Infinite Fluid Tank" (https://mods.factorio.com/mod/fluid-memory-storage): allowing it to connect to the signal network and read the quantity of items stored in this large tank.

**Comment by notnotmelon** [comment]
Hi, this is already a feature.

**Comment by Zaflis** [comment]
It seems there is indeed a problem with circuits, i can't connect wire so i can't read its contents:

<img width="302" height="213" alt="Image" src="https://github.com/user-attachments/assets/c3b9bda9-dd1a-4f67-98aa-e10e747e05c5" />

No other mods modify the Memory Unit building but this mod alone.
