### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by levkaster9797** [notnotmelon/deep-storage-unit#3]
Мод Цифровое хранилище (1.6.1) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event deep-storage-unit::on_nth_tick(15)
__deep-storage-unit__/control.lua:60: Arguments count error for 'spill_item_stack': Expected 1 argument but 2 were given
stack traceback:
	[C]: in function 'spill_item_stack'
	__deep-storage-unit__/control.lua:60: in function 'set_filter'
	__deep-storage-unit__/control.lua:76: in function 'detect_item'
	__deep-storage-unit__/control.lua:94: in function 'update_unit'
	__deep-storage-unit__/control.lua:135: in function <__deep-storage-unit__/control.lua:130>

**Comment by d-stephane** [comment]
Same problem for me :
![memory_storage_error](https://github.com/user-attachments/assets/332306a6-618b-4148-854d-9611a9073784)

**Comment by zrattz** [comment]
Same for me, seems to happen if the silo is empty and i add items by inserter it crashing, adding first item by hand first dosent crash
