### ISSUE TITLE
[1.6.2] Extracting items via Ctrl+LMB on mem.unit doesn't update the title with items quantity (due to spoilage?)

### ISSUE THREAD

**Issue by KirillNaumkin** [notnotmelon/deep-storage-unit#6]
Reproduce steps:
1. Insert 2 spoilable items.
2. Wait until they spoil.
3. Click Ctrl+LMB on mem.unit.
4. Items extracted and...
Bug: ...items counter didn't update — it still shows 2.
Expected: ...items counter updated to 0 and disappeared.

Looks like MU shouldn't allow inserting spoilable items. If there's no way of "freezing" them (as if they really became digital and un-spoilable),

**Comment by notnotmelon** [comment]
This is now fixed.

![image](https://github.com/user-attachments/assets/5b879064-ba57-48e4-8d87-418ea31a350f)
