### ISSUE TITLE
[1.6.2] Why MU is undeliverable with rocket?

### ISSUE THREAD

**Issue by KirillNaumkin** [notnotmelon/deep-storage-unit#7]
There're 2 types of MUs:
1. Packed (not stackable). These ones shouldn't be deliverable to a space platform — it's ok. Like rocket-silo.
2. Empty (stackable). These ones should be deliverable to a space platform. But not placeable there. Like cargo-landing-pad.

**Comment by notnotmelon** [comment]
I believe they should be placeable in the space platform surface. It does not ruin space platform balance as they are large entity and can only can store one item type.
